# Generated by Django 3.2.4 on 2021-06-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name=20)),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='combine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=10)),
                ('attribute_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(verbose_name=20)),
                ('count', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='feature_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='group_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name=20)),
                ('product_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=10)),
                ('url', models.CharField(max_length=200)),
                ('cover', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('view', models.IntegerField(verbose_name=20)),
                ('acttive', models.IntegerField(default=1)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(verbose_name=20)),
                ('catagory_id', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='product_catogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_id', models.IntegerField(verbose_name=20)),
                ('product_id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
